"""Model configurations for all PP-OCRv3 models."""

MODELS = {
    # === Detection Models ===
    "Multilingual_PP-OCRv3_det_infer": {
        "model_id": "cycloneboy/Multilingual_PP-OCRv3_det_infer",
        "task": "ocr-detection",
        "model_file": "model.onnx",
        "has_dict": False,
        "description": "多语言 PP-OCRv3 文本检测模型",
        "tags": ["OCR", "检测", "多语言"],
    },
    "ch_PP-OCRv3_det_infer": {
        "model_id": "cycloneboy/ch_PP-OCRv3_det_infer",
        "task": "ocr-detection",
        "model_file": "model.onnx",
        "has_dict": False,
        "description": "中文 PP-OCRv3 文本检测模型",
        "tags": ["OCR", "检测", "中文"],
    },
    "en_PP-OCRv3_det_infer": {
        "model_id": "cycloneboy/en_PP-OCRv3_det_infer",
        "task": "ocr-detection",
        "model_file": "model.onnx",
        "has_dict": False,
        "description": "英文 PP-OCRv3 文本检测模型",
        "tags": ["OCR", "检测", "英文"],
    },
    "en_PP-OCRv3_det_infer_somohk": {
        "model_id": "somohk/en_PP-OCRv3_det_infer",
        "task": "ocr-detection",
        "model_file": "model.onnx",
        "has_dict": False,
        "dir_name": "en_PP-OCRv3_det_infer_somohk",
        "description": "英文 PP-OCRv3 文本检测模型 (somohk)",
        "tags": ["OCR", "检测", "英文"],
    },

    # === Recognition Models ===
    "arabic_PP-OCRv3_rec_infer": {
        "model_id": "cycloneboy/arabic_PP-OCRv3_rec_infer",
        "task": "ocr-recognition",
        "model_file": "model.onnx",
        "has_dict": True,
        "description": "阿拉伯语 PP-OCRv3 文本识别模型",
        "tags": ["OCR", "识别", "阿拉伯语"],
    },
    "ch_PP-OCRv3_rec_infer": {
        "model_id": "cycloneboy/ch_PP-OCRv3_rec_infer",
        "task": "ocr-recognition",
        "model_file": "model.onnx",
        "has_dict": True,
        "description": "中文 PP-OCRv3 文本识别模型",
        "tags": ["OCR", "识别", "中文"],
    },
    "chinese_cht_PP-OCRv3_rec_infer": {
        "model_id": "cycloneboy/chinese_cht_PP-OCRv3_rec_infer",
        "task": "ocr-recognition",
        "model_file": "model.onnx",
        "has_dict": True,
        "description": "繁体中文 PP-OCRv3 文本识别模型",
        "tags": ["OCR", "识别", "繁体中文"],
    },
    "cyrillic_PP-OCRv3_rec_infer": {
        "model_id": "cycloneboy/cyrillic_PP-OCRv3_rec_infer",
        "task": "ocr-recognition",
        "model_file": "model.onnx",
        "has_dict": True,
        "description": "西里尔字母 PP-OCRv3 文本识别模型",
        "tags": ["OCR", "识别", "西里尔"],
    },
    "devanagari_PP-OCRv3_rec_infer": {
        "model_id": "cycloneboy/devanagari_PP-OCRv3_rec_infer",
        "task": "ocr-recognition",
        "model_file": "model.onnx",
        "has_dict": True,
        "description": "天城文 PP-OCRv3 文本识别模型",
        "tags": ["OCR", "识别", "天城文"],
    },
    "en_PP-OCRv3_rec_infer": {
        "model_id": "cycloneboy/en_PP-OCRv3_rec_infer",
        "task": "ocr-recognition",
        "model_file": "model.onnx",
        "has_dict": True,
        "description": "英文 PP-OCRv3 文本识别模型",
        "tags": ["OCR", "识别", "英文"],
    },
    "japan_PP-OCRv3_rec_infer": {
        "model_id": "cycloneboy/japan_PP-OCRv3_rec_infer",
        "task": "ocr-recognition",
        "model_file": "model.onnx",
        "has_dict": True,
        "description": "日文 PP-OCRv3 文本识别模型",
        "tags": ["OCR", "识别", "日文"],
    },
    "ka_PP-OCRv3_rec_infer": {
        "model_id": "cycloneboy/ka_PP-OCRv3_rec_infer",
        "task": "ocr-recognition",
        "model_file": "model.onnx",
        "has_dict": True,
        "description": "格鲁吉亚语 PP-OCRv3 文本识别模型",
        "tags": ["OCR", "识别", "格鲁吉亚语"],
    },
    "korean_PP-OCRv3_rec_infer": {
        "model_id": "cycloneboy/korean_PP-OCRv3_rec_infer",
        "task": "ocr-recognition",
        "model_file": "model.onnx",
        "has_dict": True,
        "description": "韩文 PP-OCRv3 文本识别模型",
        "tags": ["OCR", "识别", "韩文"],
    },
    "latin_PP-OCRv3_rec_infer": {
        "model_id": "cycloneboy/latin_PP-OCRv3_rec_infer",
        "task": "ocr-recognition",
        "model_file": "model.onnx",
        "has_dict": True,
        "description": "拉丁字母 PP-OCRv3 文本识别模型",
        "tags": ["OCR", "识别", "拉丁字母"],
    },
    "ta_PP-OCRv3_rec_infer": {
        "model_id": "cycloneboy/ta_PP-OCRv3_rec_infer",
        "task": "ocr-recognition",
        "model_file": "model.onnx",
        "has_dict": True,
        "description": "泰米尔语 PP-OCRv3 文本识别模型",
        "tags": ["OCR", "识别", "泰米尔语"],
    },
    "te_PP-OCRv3_rec_infer": {
        "model_id": "cycloneboy/te_PP-OCRv3_rec_infer",
        "task": "ocr-recognition",
        "model_file": "model.onnx",
        "has_dict": True,
        "description": "泰卢固语 PP-OCRv3 文本识别模型",
        "tags": ["OCR", "识别", "泰卢固语"],
    },
}
